apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: {{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "labels.standard" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.prefix | lower }}/{{ .Chart.Name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/status
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health/status
              port: http
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: "0.5"
              memory: 512Mi
            limits:
              cpu: "0.5"
